<a href="https://colab.research.google.com/github/Arul-Vincy-Mary/nerd/blob/main/Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import required libraries
import os
import csv
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from numpy import mean, sqrt, square

In [2]:
#current working directory
os.getcwd()

'/content'

In [3]:
#changing the working directory
os.chdir('/content/drive/MyDrive/gestures-dataset')

In [4]:
#list the directory
os.listdir()

['U01', 'U02', 'U03', 'U04', 'U05', 'U06', 'U07', 'U08']

In [5]:
#statistical features of the data
def features(data):
  column = data.columns
  lists = []

  for i in column:
    mean = data[i].mean()
    lists.append(mean)
    median = data[i].median()
    lists.append(median)
    rms_value = np.sqrt(np.mean(np.square(data[i])))
    lists.append(rms_value)
    var = data[i].var()
    lists.append(var)
    std = data[i].std()
    lists.append(std)
    kurt = data[i].kurtosis()
    lists.append(kurt)
    skew = data[i].skew()
    lists.append(skew)
  return lists

In [6]:
#flatten 
def flatten(values):
  lists_1 = []
  for sub_list in values:
    for item in sub_list:
      lists_1.append(item)
  return lists_1 

In [7]:
#sampling
def sample(data):
  data_1 = data.sample(n=10, replace=True)
  col = data.columns
  val = []
  for i in col:
   q = data_1[i]. tolist()
   val.append(q)
  val = flatten(val)
  return val  

In [ ]:
data_1 = pd.DataFrame(columns=['C' +str(x) for x in range(1,53)])
home_path= os.getcwd()
directory= os.listdir()
for dir in directory:
  path = home_path + '/'+ dir
  os.chdir(home_path + '/' + dir)
  directory_1 = os.listdir(path)
  for sub_directory in directory_1:
    path_1 = home_path + '/' +dir+ '/' + sub_directory
    os.chdir(home_path + '/' +dir+ '/' + sub_directory)
    path_1 = os.listdir(path_1)
    for file_name in path_1:
      file_path = print(home_path + '/' +dir+ '/' + sub_directory+ '/' +file_name)
      ges_data = []
      data = pd.read_csv(file_name, sep = " ")
      data.columns = ['time_stamp1','time_stamp2','time_stamp3','roll','pitch','yaw']
      data = data.drop(['time_stamp1','time_stamp2','time_stamp3'], axis= 1)
      features_1 = features(data)
      sample_1 = sample(data)
      ges_data = features_1 + sample_1+[sub_directory]
      df= pd.DataFrame([ges_data], columns=['C' +str(x) for x in range(1,53)])
      data_1 = pd.concat([data_1,df])

In [9]:
#rest the index
new_data = data_1.reset_index(drop=True)

In [10]:
#copy of the dataste
gesture = new_data.copy(deep=True)

In [11]:
#shape of the dataset
gesture.shape

(3251, 52)

In [12]:
gesture.head()

C1        C2        C3        C4  ...        C49       C50        C51  C52
0  1.426207  0.612916  2.613889  5.198213  ...  10.419566  9.193734  10.726024   01
1  1.131537  0.459687  2.441327  5.069679  ...  10.266337  8.580819   9.500193   01
2  1.720879  1.225831  2.789375  5.220789  ...  10.572795  8.887277   9.653421   01
3  1.119750 -0.153229  2.447608  5.131689  ...   9.653421  7.201759   9.193734   01
4  1.400950  0.536301  2.231047  3.246824  ...  10.419566  9.346964  10.113108   01

[5 rows x 52 columns]

Model building:

splitting data as test and train:

In [13]:
# Splitting data as test and train
from sklearn.model_selection import train_test_split
gesture_columns_list = list(gesture.columns)
features = list(set(gesture_columns_list)-set(['C52']))

x = gesture[features].values
y = gesture['C52'].values

x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.20)

In [14]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2600, 51)
(651, 51)
(2600,)
(651,)


In [15]:
# Standardising all the variables 
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [19]:
#importing libraries for knn,RF,SVM
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

KNN:

In [17]:
# Setting the K value
kclassifier = KNeighborsClassifier(n_neighbors = 3)

# Fitting the values of x and y
kclassifier.fit(x_train, y_train)

# Predicting 
prediction = kclassifier.predict(x_test)

# Accuracy Score
accuracy_score = accuracy_score(prediction, y_test)
print(accuracy_score)

0.5099846390168971


2.Random Forest:

In [35]:
# Building Random Forest model
rf = RandomForestClassifier(n_estimators= 200, criterion='gini' )
rf.fit(x_train, y_train)

# Predicting the model on test data
predictions_rf = rf.predict(x_test)

#accuracy score
print(accuracy_score(y_test, predictions_rf))

0.8433179723502304


3.Support Vector Machine:

In [57]:
#Building SVM model
svm_clf = SVC(gamma='auto',C = 10, kernel = 'rbf', random_state=None)
svm_clf.fit(x_train, y_train) 

#predicting the model on the test data
y_pred = svm_clf.predict(x_test)

#accuracy score
print(accuracy_score(y_test, y_pred))

0.7373271889400922


Hyper parameter tunning:

i) SVM:

In [67]:
from sklearn.model_selection import GridSearchCV

In [53]:
param_grid = { 'gamma': [0.01,0.1,1],
                 'C' :[0.1,1,10],
                 'kernel':['rbf','linear'],
                }

In [54]:
grid_search = GridSearchCV(estimator= svm_clf, param_grid= param_grid, cv= 10,n_jobs = -1, verbose = False)

In [55]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=10, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'gamma': [0.01, 0.1, 1],
                         'kernel': ['rbf', 'linear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=False)

In [58]:
grid_search.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

In [56]:
grid_pred = grid_search.predict(x_test)
print(accuracy_score(y_test, grid_pred))

0.7450076804915514


ii) Random Forest:

In [59]:
param_grid_1 = {'bootstrap': [True],
                'max_depth': [50, 100, 150],
                'max_features': [2, 3, 5],
                'min_samples_leaf': [3, 4, 5],
                'min_samples_split': [8, 10, 20],
                'n_estimators': [200, 500, 1000]
                }

In [60]:
grid_search_2 = GridSearchCV(estimator = rf, param_grid = param_grid_1, cv = 3, n_jobs = -1, verbose = False)

In [61]:
grid_search_3.fit(x_train, y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=200, n_jobs=None,
                                              oob_score=False,
                                              rando

In [62]:
grid_search_3.best_params_

{'bootstrap': True,
 'max_depth': 150,
 'max_features': 5,
 'min_samples_leaf': 3,
 'min_samples_split': 8,
 'n_estimators': 1000}

In [63]:
me = grid_search_3.best_estimator_

In [64]:
grid_pred_2 = me.predict(x_test)
print(accuracy_score(y_test, grid_pred_2))

0.8172043010752689


with PCA:

In [ ]:
input_columns = list(data_2.iloc[:,:51].columns)

input_data = data_2[input_columns]
input_data.head()

C1        C2        C3  ...        C49        C50        C51
0  1.426207  0.612916  2.613889  ...   9.040505   8.887277  10.726024
0  1.131537  0.459687  2.441327  ...   8.580819   9.959879   8.580819
0  1.720879  1.225831  2.789375  ...  10.113108   9.500193   8.887277
0  1.119750 -0.153229  2.447608  ...  10.419566   9.653421   9.959879
0  1.400950  0.536301  2.231047  ...  10.419566  10.419566  10.113108

[5 rows x 51 columns]

In [ ]:
# Scaling data using (x-mu)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_std = True)
input_data = scaler.fit_transform(input_data)

In [ ]:
input_data = pd.DataFrame(input_data,columns=input_columns)
input_data.head()

C1        C2        C3  ...       C49       C50       C51
0 -2.041552 -2.393595 -3.709861  ...  1.016278  0.990591  2.727249
1 -2.336223 -2.546824 -3.882423  ...  0.556592  2.063193  0.582044
2 -1.746881 -1.780680 -3.534376  ...  2.088881  1.603507  0.888502
3 -2.348010 -3.159740 -3.876143  ...  2.395339  1.756735  1.961104
4 -2.066810 -2.470209 -4.092704  ...  2.395339  2.522880  2.114333

[5 rows x 51 columns]

In [ ]:
u, s, v = np.linalg.svd(input_data)  #decomposing using SVD
gest = data_2[input_columns].dot(v.T)
gest.columns= ['col' +str(x) for x in range(1,52)]
gest

col1       col2       col3  ...     col49     col50     col51
0    2.981757   0.930167  -6.504309  ...  0.091341  2.003784  1.404924
0    2.562786   1.175193  -5.584769  ... -0.086144  2.085640  1.412180
0    4.421553   1.876080  -7.486937  ... -0.124726  1.963769  0.982767
0    2.478851   1.608154  -2.689707  ... -0.214402  2.144631  1.184338
0    1.230209   2.857414  -4.377300  ...  0.097299  1.989754  1.432770
..        ...        ...        ...  ...       ...       ...       ...
0   15.686263 -11.742349 -18.587256  ...  0.022295  2.039759  1.349730
0   14.702644  -9.732140 -21.165209  ...  0.109955  1.835372  1.351142
0   11.417464  -8.994988 -17.530943  ...  0.135139  1.957301  1.407601
0   11.885981  -6.556423 -18.297389  ...  0.061665  1.937175  1.423841
0   15.459157 -10.577163 -23.134482  ...  0.259467  1.935716  1.436081

[3251 rows x 51 columns]

In [ ]:
gest['col52']= data_2['C52']
gest.head()

col1      col2      col3      col4  ...     col49     col50     col51  col52
0  2.981757  0.930167 -6.504309  4.145298  ...  0.091341  2.003784  1.404924     01
0  2.562786  1.175193 -5.584769  4.382689  ... -0.086144  2.085640  1.412180     01
0  4.421553  1.876080 -7.486937  5.805088  ... -0.124726  1.963769  0.982767     01
0  2.478851  1.608154 -2.689707  5.834392  ... -0.214402  2.144631  1.184338     01
0  1.230209  2.857414 -4.377300  3.648867  ...  0.097299  1.989754  1.432770     01

[5 rows x 52 columns]

In [ ]:
exp_var=s**2/np.sum(s**2)*100  # Explained variance by each eigen value/PC
exp_var
exp_variences = []
for i in range(len(s)):
    exp_variences.append(s[i] / np.sum(s))

#print(np.sum(exp_variences))
#print(exp_variences)
#sum(exp_variences[:51])

In [ ]:
from sklearn.decomposition import PCA 
# Choosing the extent of variance to be covered by the PCs
pca = PCA(n_components=30)

# Transforming the iris data input_columns
pca_data = pca.fit_transform(gest.iloc[:,:51])

# Storing the PCs in the data frame
pca_data_df = pd.DataFrame(pca_data, columns=['col' +str(x) for x in range(1,31)])
	
pca_data_df_with_class = pd.concat([pca_data_df, gest['col52']], axis=0)

print('Explained variance :\n')
print(sum(pca.explained_variance_ratio_))

Explained variance :

0.9743168365054763


In [ ]:
data_3 = pca_data_df.copy()

# Creating a copy of data_2
x = data_3.copy()

# Splitting into train and test data
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.3, random_state =0)


In [ ]:
# Standardising all the variables 
scalar = StandardScaler()
scalar.fit(train_x)
train_x = scalar.transform(train_x)
test_x = scalar.transform(test_x)

In [ ]:
# Random Forest 
from sklearn.metrics import accuracy_score,confusion_matrix
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier

# Building Random Forest
rf = RandomForestClassifier(n_estimators=200, random_state=0)
rf.fit(train_x, train_y)

pred_rf = rf.predict(test_x) 

# Confusion Matrix
print(confusion_matrix(test_y,pred_rf))
# Accuracy Score
print(accuracy_score(test_y,pred_rf))


[[23 25  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  1  0  0]
 [11 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1]
 [ 2  0 31  4  0  0  0  0  4  2  0  1  0  0  0  0  0  1  1  1]
 [ 1  0  3 37  2  0  0  0  1  1  2  4  3  1  0  1  0  0  0  0]
 [ 0  0  0  0 24 11  2  0  0  0  0  0  0  0  1  1  1  1  0  0]
 [ 0  0  0  1  7 35  2  0  0  0  4  1  0  0  1  0  0  0  0  0]
 [ 0  0  0  1  8  5 20 10  1  1  2  2  0  0  1  0  2  0  1  0]
 [ 0  0  0  1  8  9  3 16  0  3  3  6  0  0  2  1  0  0  0  0]
 [ 1  0  3  0  0  0  6  8 14 10  0  0  0  1  0  0  0  0  2  0]
 [ 0  0  1  0  1  0  5  3  9 20  0  1  0  1  0  0  1  0  2  2]
 [ 0  0  0  1  1  2  3  5  1  2 24  4  0  3  0  0  1  2  2  3]
 [ 0  0  0  2  5  1  0  1  5  1  3 18  0  3  0  2  1  2  1  2]
 [ 0  0  5  3  0  0  0  0  3  2  0  3 28  8  0  0  0  0  1  1]
 [ 0  0  5  4  0  0  2  2  1  1  0  0 14 17  1  2  1  0  2  1]
 [ 0  0  0  1  4  2  0  0  0  0  1  0  0  0 25 11  0  0  0  0]
 [ 0  0  0  2  3  1  0  0  0  0  3  0  0  0  7 36  0  0

In [ ]:
# Importing the required libraries 
from sklearn.neighbors import KNeighborsClassifier

# Setting the K value
kclassifier = KNeighborsClassifier(n_neighbors = 3)

# Fitting the values of x and y
kclassifier.fit(train_x, train_y)

# Predicting 
prediction = kclassifier.predict(test_x)

# Confusion Matrix
confusion_matrix = confusion_matrix(prediction, test_y)
print(confusion_matrix)

# Accuracy Score
accuracy_score = accuracy_score(prediction, test_y)
print(accuracy_score)



[[19 18  0  2  0  0  0  0  1  2  2  0  0  0  1  1  2  2  0  1]
 [31 21  0  1  0  0  2  1  1  0  2  0  0  0  0  0  2  2  0  1]
 [ 0  0 28  8  0  0  0  1  3  5  2  3  7  8  0  0  0  0  4  1]
 [ 0  0  4 33  3  4  3  4  3  1  5 13  4  5  2  3  0  1  2  2]
 [ 0  0  1  1 25 15 10 17  0  0  3  2  0  0  5  3  1  2  1  0]
 [ 0  0  0  1  5 21  5  7  1  1  5  0  0  1  0  2  1  1  0  0]
 [ 0  0  1  1  2  5 16  7  5  5  3  4  0  2  1  3  0  0  0  0]
 [ 1  0  0  0  2  3  8  8  2  2  2  3  0  2  0  3  0  0  0  0]
 [ 0  0  3  3  0  0  2  1 17  8  2  1  5  3  0  0  1  0  2  0]
 [ 0  0  5  2  0  0  1  1  6 19  1  1  2  1  0  0  0  0  0  1]
 [ 0  0  0  2  0  2  3  1  0  1 21  6  1  0  3  2  2  1  0  1]
 [ 0  0  2  1  2  0  4  4  0  0  1  9  0  0  0  0  1  0  1  1]
 [ 0  0  1  1  0  0  0  0  2  0  1  0 22 12  0  0  0  0  2  0]
 [ 0  0  2  0  0  0  0  0  3  1  1  1 13 19  0  0  0  0  0  0]
 [ 0  0  0  0  2  1  0  0  0  0  0  0  0  0 20 11  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0 12 24  0  0

SVM:

In [ ]:
svm_clf = SVC(gamma="scale",C = 10, kernel = 'rbf', degree = 3, random_state=None)
svm_clf.fit(train_x, train_y)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
pred_y = svm_clf.predict(train_x)
print(accuracy_score(train_y, pred_y))

0.9213186813186813
